sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
  - sudo apt-get install fuse
install:
  - pip install -r tests/requirements.txt
script:
  - coverage run -m unittest tests
after_success:
  - coveralls
